# Generated by Django 5.1 on 2024-08-09 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_saleproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='shop.product'),
        ),
    ]
